import type { Metadata } from 'next'
import '@mantine/core/styles.css'
import { Plus_Jakarta_Sans } from 'next/font/google'
import './globals.css'
import { Box, ColorSchemeScript, MantineProvider } from '@mantine/core'
import appTheme from '@/theme'

const jakarta = Plus_Jakarta_Sans({
  weight: ['400', '500', '700'],
  style: 'normal',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Chatter',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${jakarta.className}`}>
        <ColorSchemeScript />
        <MantineProvider theme={appTheme}>
          <Box maw={1850} mx='auto'>
            {children}
          </Box>
        </MantineProvider>
      </body>
    </html>
  )
}
