import '@mantine/core/styles.css'

import { Box, ColorSchemeScript, MantineProvider } from '@mantine/core'
import theme from '@/theme'
import type { Metadata } from 'next'
import { Plus_Jakarta_Sans } from 'next/font/google'
import './globals.css'

const jakarta = Plus_Jakarta_Sans({
  weight: ['400', '500', '700'],
  style: 'normal',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Chatter',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <head>
        <ColorSchemeScript />
        <meta
          name='viewport'
          content='minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no'
        />
      </head>
      <body className={`${jakarta.className}`}>
        <MantineProvider theme={theme}>
          <Box maw={1850} mx='auto'>
            {children}
          </Box>
        </MantineProvider>
      </body>
    </html>
  )
}
